require('dotenv').config({ path: '../.env' });
const pool = require('./db');
const bcrypt = require('bcryptjs');

const categories = {
  characters: [
    { name: 'Thorn Ironveil', description: 'A battle-scarred paladin seeking redemption in the Ashen Wastes.', metadata: { class: 'Paladin', race: 'Human', level: 12, hp: 145, mp: 60, strength: 18, dexterity: 10, intelligence: 14, alignment: 'Lawful Good' }, image_prompt: 'A tall human paladin in dented silver armor with glowing runes, standing before a ruined temple' },
    { name: 'Lyria Moonwhisper', description: 'An elven sorceress who channels starlight into devastating arcane blasts.', metadata: { class: 'Sorceress', race: 'Elf', level: 15, hp: 80, mp: 200, strength: 8, dexterity: 14, intelligence: 22, alignment: 'Chaotic Good' }, image_prompt: 'An elegant elf woman with silver hair channeling swirling starlight between her hands' },
    { name: 'Grukk the Unyielding', description: 'An orc berserker who fights with two axes and an unquenchable thirst for glory.', metadata: { class: 'Berserker', race: 'Orc', level: 10, hp: 200, mp: 10, strength: 22, dexterity: 12, intelligence: 6, alignment: 'Chaotic Neutral' }, image_prompt: 'A massive green orc dual-wielding battle axes with war paint on his face' },
    { name: 'Sable Nightrose', description: 'A half-elf rogue who operates a network of spies across three kingdoms.', metadata: { class: 'Rogue', race: 'Half-Elf', level: 14, hp: 95, mp: 40, strength: 12, dexterity: 20, intelligence: 16, alignment: 'Neutral' }, image_prompt: 'A hooded half-elf woman in dark leather armor with twin daggers, shrouded in shadow' },
    { name: 'Brother Aldric', description: 'A dwarven cleric devoted to the forge god, healing allies with molten prayer.', metadata: { class: 'Cleric', race: 'Dwarf', level: 11, hp: 130, mp: 120, strength: 16, dexterity: 8, intelligence: 14, alignment: 'Lawful Neutral' }, image_prompt: 'A stout dwarf cleric in heavy robes with a glowing hammer-shaped holy symbol' },
    { name: 'Zephyr Windrider', description: 'A gnome artificer who built her own mechanical wings.', metadata: { class: 'Artificer', race: 'Gnome', level: 9, hp: 70, mp: 90, strength: 8, dexterity: 16, intelligence: 20, alignment: 'Neutral Good' }, image_prompt: 'A small gnome with goggles and brass mechanical wings hovering above a workshop' },
    { name: 'Kaelen Duskwalker', description: 'A tiefling warlock bound to a shadow entity from the Void Between.', metadata: { class: 'Warlock', race: 'Tiefling', level: 13, hp: 90, mp: 150, strength: 10, dexterity: 14, intelligence: 18, alignment: 'Neutral Evil' }, image_prompt: 'A tiefling with curved horns and glowing purple eyes, dark tendrils swirling around him' },
    { name: 'Mira Sunshard', description: 'A human monk who channels solar ki through martial techniques.', metadata: { class: 'Monk', race: 'Human', level: 10, hp: 100, mp: 80, strength: 14, dexterity: 20, intelligence: 12, alignment: 'Lawful Good' }, image_prompt: 'A bald woman monk with golden tattoos glowing on her arms, in a fighting stance' },
    { name: 'Fenwick Bramblewood', description: 'A halfling ranger who commands a pack of dire wolves.', metadata: { class: 'Ranger', race: 'Halfling', level: 8, hp: 85, mp: 50, strength: 12, dexterity: 18, intelligence: 12, alignment: 'Neutral Good' }, image_prompt: 'A small halfling ranger with a longbow standing among three large wolves in a forest' },
    { name: 'Vorathis the Unbound', description: 'A dragonborn wizard who specializes in gravitational magic.', metadata: { class: 'Wizard', race: 'Dragonborn', level: 16, hp: 75, mp: 220, strength: 14, dexterity: 10, intelligence: 24, alignment: 'Lawful Neutral' }, image_prompt: 'A blue-scaled dragonborn in arcane robes levitating objects around him with gravity magic' },
    { name: 'Isolde Frostbloom', description: 'A winter fey knight exiled from the Unseelie Court.', metadata: { class: 'Knight', race: 'Fey', level: 14, hp: 120, mp: 100, strength: 16, dexterity: 16, intelligence: 14, alignment: 'Chaotic Neutral' }, image_prompt: 'An ethereal fey woman in icy crystalline armor with frost flowers growing around her' },
    { name: 'Raskhar Emberfang', description: 'A kobold sorcerer who accidentally absorbed a dragon\'s dying breath.', metadata: { class: 'Sorcerer', race: 'Kobold', level: 7, hp: 50, mp: 130, strength: 6, dexterity: 16, intelligence: 16, alignment: 'Chaotic Good' }, image_prompt: 'A tiny kobold crackling with red draconic energy, flames dripping from his claws' },
    { name: 'Dame Seraphina Voss', description: 'A legendary human general who has never lost a siege.', metadata: { class: 'Fighter', race: 'Human', level: 18, hp: 210, mp: 20, strength: 20, dexterity: 14, intelligence: 16, alignment: 'Lawful Good' }, image_prompt: 'A commanding woman in ornate plate armor with a massive war banner behind her' },
    { name: 'Nyx Hollowshade', description: 'A changeling bard who has lived a hundred different lives.', metadata: { class: 'Bard', race: 'Changeling', level: 11, hp: 80, mp: 110, strength: 10, dexterity: 14, intelligence: 16, alignment: 'Chaotic Neutral' }, image_prompt: 'A pale figure with shifting features playing a lute that emanates visible sound waves' },
    { name: 'Tormund Ashbeard', description: 'A fire giant diplomat trying to forge peace between giants and smallfolk.', metadata: { class: 'Diplomat', race: 'Fire Giant', level: 20, hp: 350, mp: 40, strength: 26, dexterity: 8, intelligence: 14, alignment: 'Neutral Good' }, image_prompt: 'A massive fire giant in formal attire with a braided flaming beard, extending a hand in peace' },
  ],
  weapons: [
    { name: 'Frostbite Edge', description: 'A longsword forged in a glacier that freezes wounds it inflicts.', metadata: { damage: '2d8+3 cold', type: 'Longsword', rarity: 'Rare', weight: 4, range: 'Melee', element: 'Ice', bonus: '+3', required_level: 8 }, image_prompt: 'A gleaming longsword coated in frost with ice crystals forming along the blade' },
    { name: 'Sunfire Bow', description: 'A composite bow that ignites arrows as they are nocked.', metadata: { damage: '1d10+4 fire', type: 'Bow', rarity: 'Very Rare', weight: 3, range: '150ft', element: 'Fire', bonus: '+4', required_level: 12 }, image_prompt: 'An ornate golden bow with flame-wreathed arrows on a string of pure light' },
    { name: 'The Betrayer', description: 'A cursed dagger that deals extra damage to allies.', metadata: { damage: '1d4+6 necrotic', type: 'Dagger', rarity: 'Legendary', weight: 1, range: 'Melee', element: 'Shadow', bonus: '+6', required_level: 15, cursed: true }, image_prompt: 'A sleek black dagger dripping with shadow energy, the blade seems to whisper' },
    { name: 'Stormcaller Staff', description: 'A gnarled staff topped with a perpetually crackling orb of lightning.', metadata: { damage: '3d6 lightning', type: 'Staff', rarity: 'Rare', weight: 5, range: '60ft', element: 'Lightning', bonus: '+3', required_level: 10 }, image_prompt: 'A twisted wooden staff with a sphere of contained lightning at its peak' },
    { name: 'Earthshaker Maul', description: 'A colossal warhammer that creates fissures on impact.', metadata: { damage: '2d12+5 bludgeoning', type: 'Maul', rarity: 'Very Rare', weight: 12, range: 'Melee', element: 'Earth', bonus: '+5', required_level: 14 }, image_prompt: 'A massive stone and iron warhammer with cracks of golden energy running through it' },
    { name: 'Whisper of Lethalis', description: 'A rapier so thin it seems to vanish when turned sideways.', metadata: { damage: '1d8+4 piercing', type: 'Rapier', rarity: 'Rare', weight: 2, range: 'Melee', element: 'None', bonus: '+4', required_level: 9, special: 'Ignores armor' }, image_prompt: 'An impossibly thin rapier that seems to phase in and out of visibility' },
    { name: 'Voidcannon', description: 'A hand-held arcane cannon that fires compressed void energy.', metadata: { damage: '4d8 force', type: 'Firearm', rarity: 'Legendary', weight: 8, range: '120ft', element: 'Void', bonus: '+5', required_level: 16 }, image_prompt: 'A dark metal cannon with swirling purple void energy in its barrel' },
    { name: 'Thornlash Whip', description: 'A living vine whip covered in poisonous thorns.', metadata: { damage: '1d6+3 piercing + 1d4 poison', type: 'Whip', rarity: 'Uncommon', weight: 2, range: '15ft', element: 'Nature', bonus: '+3', required_level: 6 }, image_prompt: 'A green living vine whip with sharp thorns dripping violet poison' },
    { name: 'Aegis Gauntlets', description: 'Armored fists that project force shields on impact.', metadata: { damage: '1d8+3 force', type: 'Gauntlets', rarity: 'Rare', weight: 3, range: 'Melee', element: 'Force', bonus: '+3', required_level: 8 }, image_prompt: 'Heavy metal gauntlets with glowing blue force projectors on each knuckle' },
    { name: 'Bonesaw Greataxe', description: 'An axe made from a dragon\'s jawbone, it hungers for combat.', metadata: { damage: '2d12+4 slashing', type: 'Greataxe', rarity: 'Very Rare', weight: 10, range: 'Melee', element: 'None', bonus: '+4', required_level: 12, special: 'Lifesteal' }, image_prompt: 'A brutal greataxe crafted from a massive dragon jawbone with teeth as the blade' },
    { name: 'Starfall Shurikens', description: 'Throwing stars carved from meteorite that return to the wielder.', metadata: { damage: '1d6+2 radiant', type: 'Thrown', rarity: 'Rare', weight: 0.5, range: '60ft', element: 'Radiant', bonus: '+2', required_level: 7, special: 'Returning' }, image_prompt: 'Shimmering metallic throwing stars trailing stardust as they fly through the air' },
    { name: 'Tidecaller Trident', description: 'A coral trident that commands ocean currents.', metadata: { damage: '2d6+4 piercing + 1d6 cold', type: 'Trident', rarity: 'Very Rare', weight: 6, range: 'Melee/30ft', element: 'Water', bonus: '+4', required_level: 11 }, image_prompt: 'A trident made of living coral with water swirling around its three prongs' },
    { name: 'Hex Crossbow', description: 'A repeating crossbow that curses targets on critical hits.', metadata: { damage: '1d10+3 piercing', type: 'Crossbow', rarity: 'Rare', weight: 6, range: '100ft', element: 'Curse', bonus: '+3', required_level: 9, special: 'Crit applies random curse' }, image_prompt: 'A dark wood crossbow with sinister green runes etched along its limbs' },
    { name: 'Blazing Chakram', description: 'A ring blade perpetually wreathed in divine flame.', metadata: { damage: '2d6+3 fire + radiant', type: 'Chakram', rarity: 'Rare', weight: 2, range: '40ft', element: 'Fire/Radiant', bonus: '+3', required_level: 10, special: 'Returning' }, image_prompt: 'A spinning ring blade engulfed in golden-white divine flames' },
    { name: 'Gravedigger', description: 'A sentient shovel that was accidentally enchanted to legendary status.', metadata: { damage: '2d10+5 bludgeoning', type: 'Improvised/Shovel', rarity: 'Legendary', weight: 5, range: 'Melee', element: 'None', bonus: '+5', required_level: 13, special: 'Speaks, can dig through anything' }, image_prompt: 'A battered iron shovel radiating immense magical power with glowing eyes on the blade' },
  ],
  environments: [
    { name: 'The Shattered Expanse', description: 'Floating islands of rock drift over an endless void, connected by ancient chains.', metadata: { biome: 'Floating Islands', climate: 'Windy/Cold', danger_level: 7, resources: ['skystone', 'wind essence', 'chain iron'], creatures: ['Sky Serpents', 'Wind Elementals'], lighting: 'Perpetual dusk' }, image_prompt: 'Massive floating rock islands connected by rusted chains over a purple void' },
    { name: 'Verdant Abyss', description: 'A jungle that grows downward into a massive sinkhole, getting stranger with each layer.', metadata: { biome: 'Underground Jungle', climate: 'Humid/Hot', danger_level: 8, resources: ['bioluminescent sap', 'deep roots', 'abyssal fungi'], creatures: ['Giant Insects', 'Vine Lurkers'], lighting: 'Bioluminescent' }, image_prompt: 'A lush jungle growing downward into a deep glowing sinkhole with strange plants' },
    { name: 'Ashen Citadel Ruins', description: 'The remains of a once-great fortress, now covered in volcanic ash and smoldering.', metadata: { biome: 'Volcanic Ruins', climate: 'Hot/Dry', danger_level: 6, resources: ['obsidian', 'ash steel', 'ember crystals'], creatures: ['Fire Sprites', 'Ash Golems'], lighting: 'Orange glow from lava veins' }, image_prompt: 'Crumbling castle ruins covered in grey ash with rivers of lava running through' },
    { name: 'Crystal Caverns of Lumia', description: 'Vast underground caves filled with enormous crystals that sing when touched.', metadata: { biome: 'Crystal Cave', climate: 'Cool/Dry', danger_level: 4, resources: ['resonance crystal', 'harmonic dust', 'prismatic shards'], creatures: ['Crystal Bats', 'Living Geodes'], lighting: 'Prismatic refracted light' }, image_prompt: 'Enormous colorful crystals filling a vast cave, refracting light into rainbows' },
    { name: 'The Drowned Market', description: 'An underwater bazaar in a sunken city where merfolk and surface traders meet.', metadata: { biome: 'Underwater City', climate: 'Temperate/Submerged', danger_level: 3, resources: ['pearl currency', 'coral goods', 'sea silk'], creatures: ['Merfolk', 'Giant Seahorses'], lighting: 'Filtered sunlight and magic lanterns' }, image_prompt: 'An underwater marketplace in sunken stone buildings with merfolk merchants and air bubbles' },
    { name: 'Wraithwood', description: 'A forest where the trees are petrified and the fog takes the shape of the dead.', metadata: { biome: 'Haunted Forest', climate: 'Cold/Foggy', danger_level: 9, resources: ['spirit wood', 'ectoplasm', 'ghost lantern'], creatures: ['Wraiths', 'Shadow Wolves', 'Banshees'], lighting: 'Pale moonlight through fog' }, image_prompt: 'A grey petrified forest with ghostly shapes forming in thick rolling fog' },
    { name: 'Clockwork Foundry', description: 'A massive underground factory run by automatons, still producing unknown machines.', metadata: { biome: 'Mechanical Dungeon', climate: 'Warm/Steamy', danger_level: 6, resources: ['gears', 'steam cores', 'mithril wire'], creatures: ['Clockwork Sentries', 'Steam Golems'], lighting: 'Furnace glow and sparks' }, image_prompt: 'A massive underground factory with conveyor belts, gears, and steam-powered automaton workers' },
    { name: 'Sunblasted Desert of Khor', description: 'An endless desert where mirages come to life and attack travelers.', metadata: { biome: 'Desert', climate: 'Extremely Hot/Arid', danger_level: 7, resources: ['sun glass', 'mirage essence', 'sandworm hide'], creatures: ['Mirage Beasts', 'Sandworms', 'Sun Scorpions'], lighting: 'Blinding daylight' }, image_prompt: 'A vast golden desert with shimmering heat mirages taking monstrous forms' },
    { name: 'The Eternal Glacier', description: 'A moving glacier the size of a continent with an ancient civilization frozen inside.', metadata: { biome: 'Glacier', climate: 'Extreme Cold', danger_level: 8, resources: ['eternal ice', 'frozen artifacts', 'cryo crystals'], creatures: ['Frost Giants', 'Ice Wraiths'], lighting: 'Blue-white ice glow' }, image_prompt: 'A colossal glacier with frozen buildings and figures visible deep inside the blue ice' },
    { name: 'Mushroom Highlands', description: 'Rolling hills covered in massive mushrooms instead of trees, with spore-filled air.', metadata: { biome: 'Fungal Hills', climate: 'Mild/Damp', danger_level: 5, resources: ['spore sacs', 'mushroom timber', 'mycelium thread'], creatures: ['Sporelings', 'Fungal Bears'], lighting: 'Soft bioluminescent glow' }, image_prompt: 'Rolling green hills dotted with enormous colorful mushrooms the size of trees' },
    { name: 'The Bleeding Rift', description: 'A tear in reality where the material plane meets the Abyss, crimson energy leaking through.', metadata: { biome: 'Planar Rift', climate: 'Chaotic/Unpredictable', danger_level: 10, resources: ['rift essence', 'abyssal ore', 'chaos fragments'], creatures: ['Demons', 'Reality Shards'], lighting: 'Crimson pulsing glow' }, image_prompt: 'A massive glowing red tear in the sky with demonic energy spilling out onto scorched ground' },
    { name: 'Skyport Nimbus', description: 'A bustling city built on clouds, held aloft by ancient wind magic.', metadata: { biome: 'Cloud City', climate: 'Cool/Breezy', danger_level: 2, resources: ['cloud cotton', 'sky iron', 'wind gems'], creatures: ['Griffins', 'Air Elementals'], lighting: 'Bright open sky' }, image_prompt: 'A grand city of white stone and gold spires built on solid clouds high above the world' },
    { name: 'The Bone Marsh', description: 'A swamp filled with the skeletons of ancient megafauna, radiating necromantic energy.', metadata: { biome: 'Necro Swamp', climate: 'Warm/Humid', danger_level: 8, resources: ['bone calcium', 'death essence', 'swamp gas'], creatures: ['Skeletal Beasts', 'Bog Zombies', 'Will-o-Wisps'], lighting: 'Sickly green glow' }, image_prompt: 'A dark swamp with enormous dinosaur-like skeletons protruding from murky green water' },
    { name: 'Prismatic Falls', description: 'A waterfall that cascades through all colors of the spectrum, each color granting different effects.', metadata: { biome: 'Magical Falls', climate: 'Temperate/Misty', danger_level: 3, resources: ['prismatic water', 'rainbow stone', 'color essence'], creatures: ['Prismatic Fish', 'Color Sprites'], lighting: 'Constantly shifting rainbow' }, image_prompt: 'A magnificent waterfall cycling through vivid rainbow colors cascading into a crystalline pool' },
    { name: 'Irondeep Mines', description: 'Abandoned dwarven mines that reach so deep they breach into the Underdark.', metadata: { biome: 'Deep Mine', climate: 'Cool/Dark', danger_level: 7, resources: ['deep iron', 'shadow gems', 'mithril ore'], creatures: ['Cave Trolls', 'Dark Crawlers', 'Mine Specters'], lighting: 'Near total darkness with faint ore glow' }, image_prompt: 'A vast abandoned mine shaft going impossibly deep with faintly glowing ore veins in the walls' },
  ],
  items: [
    { name: 'Amulet of Echoing Thoughts', description: 'Allows the wearer to hear the surface thoughts of nearby creatures.', metadata: { type: 'Amulet', rarity: 'Rare', slot: 'Neck', effect: 'Detect Thoughts 3/day', weight: 0.2, value: 4500 }, image_prompt: 'A silver amulet with a swirling blue gem that pulses like a heartbeat' },
    { name: 'Bag of Endless Snacks', description: 'A small pouch that always produces a random tasty snack when reached into.', metadata: { type: 'Wondrous', rarity: 'Common', slot: 'None', effect: 'Produces food', weight: 0.5, value: 200 }, image_prompt: 'A worn leather pouch with crumbs around it and a golden pretzel peeking out' },
    { name: 'Clockwork Spider Scout', description: 'A tiny mechanical spider that can be sent to scout ahead and report back.', metadata: { type: 'Construct', rarity: 'Uncommon', slot: 'None', effect: 'Remote scouting 500ft range', weight: 0.3, value: 1500, uses: 'Unlimited' }, image_prompt: 'A tiny brass mechanical spider with glowing red eyes and articulated legs' },
    { name: 'Decanter of Purification', description: 'Any liquid poured into this decanter becomes pure, drinkable water.', metadata: { type: 'Decanter', rarity: 'Uncommon', slot: 'None', effect: 'Purify liquids', weight: 1, value: 800 }, image_prompt: 'An ornate crystal decanter that glows faintly blue when filled with liquid' },
    { name: 'Everburning Lantern', description: 'A lantern that never goes out and changes color based on nearby danger.', metadata: { type: 'Lantern', rarity: 'Uncommon', slot: 'Off-hand', effect: '60ft bright light, danger detection', weight: 1.5, value: 1200 }, image_prompt: 'A brass lantern with an eternal flame that shifts between green, yellow, and red' },
    { name: 'Featherfall Token', description: 'A single-use token that activates when the holder falls more than 10 feet.', metadata: { type: 'Token', rarity: 'Common', slot: 'None', effect: 'Feather Fall once', weight: 0.1, value: 100, consumable: true }, image_prompt: 'A small white feather encased in a clear resin disc on a string' },
    { name: 'Gloves of the Arcane Scribe', description: 'Gloves that allow the wearer to write at incredible speed by thought alone.', metadata: { type: 'Gloves', rarity: 'Uncommon', slot: 'Hands', effect: 'Telepathic writing, 10x speed', weight: 0.2, value: 900 }, image_prompt: 'Thin blue silk gloves with glowing runes that leave trails of light in the air' },
    { name: 'Healing Salve Jar', description: 'A ceramic jar that slowly regenerates a potent healing salve overnight.', metadata: { type: 'Consumable', rarity: 'Rare', slot: 'None', effect: 'Produces 1 dose (2d8+4 healing) per day', weight: 0.5, value: 3000 }, image_prompt: 'A small clay jar with a green glowing salve and leaf-patterned lid' },
    { name: 'Immovable Rod', description: 'A rod that, when activated, becomes fixed in space regardless of forces applied.', metadata: { type: 'Rod', rarity: 'Uncommon', slot: 'None', effect: 'Fixes position in space', weight: 2, value: 1000 }, image_prompt: 'A plain iron rod with a single button, floating impossibly in midair' },
    { name: 'Jumble Dice', description: 'A set of dice that, when rolled, cause a random minor magical effect.', metadata: { type: 'Wondrous', rarity: 'Common', slot: 'None', effect: 'Random minor magical effect', weight: 0.1, value: 150, charges: 'Unlimited' }, image_prompt: 'A set of six glowing multicolored dice hovering slightly above a felt pouch' },
    { name: 'Keystone of Passage', description: 'A stone key that can open any mundane lock once per day.', metadata: { type: 'Key', rarity: 'Rare', slot: 'None', effect: 'Open any non-magical lock 1/day', weight: 0.3, value: 2500 }, image_prompt: 'A smooth stone carved into a key shape with faintly glowing cracks running through it' },
    { name: 'Lorekeeper Monocle', description: 'A monocle that reveals the history of any object examined through it.', metadata: { type: 'Eyewear', rarity: 'Rare', slot: 'Eyes', effect: 'Object history reading', weight: 0.1, value: 3500 }, image_prompt: 'A golden monocle with a lens that shows swirling images of the past when peered through' },
    { name: 'Map of the Shifting Paths', description: 'A map that updates in real-time to show the terrain within 1 mile.', metadata: { type: 'Map', rarity: 'Very Rare', slot: 'None', effect: 'Real-time cartography, 1 mile radius', weight: 0.2, value: 6000 }, image_prompt: 'A leather scroll that animates with tiny moving trees, rivers, and miniature creatures' },
    { name: 'Nightvision Goggles', description: 'Dwarven-crafted goggles that grant perfect vision in total darkness.', metadata: { type: 'Goggles', rarity: 'Uncommon', slot: 'Eyes', effect: 'Darkvision 120ft', weight: 0.3, value: 1100 }, image_prompt: 'Brass and leather goggles with green-tinted lenses that glow faintly in the dark' },
    { name: 'Orb of Last Resort', description: 'A glass orb that, when shattered, teleports the user to a preset safe location.', metadata: { type: 'Orb', rarity: 'Very Rare', slot: 'None', effect: 'Emergency teleport once', weight: 0.5, value: 8000, consumable: true }, image_prompt: 'A fragile glass sphere filled with swirling golden mist and a tiny glowing rune inside' },
  ],
  monsters: [
    { name: 'Gloomfang Stalker', description: 'A six-legged shadow predator that hunts by sensing fear.', metadata: { type: 'Aberration', cr: 8, hp: 150, ac: 16, speed: '50ft', attacks: ['Shadow Bite', 'Fear Pulse', 'Phase Strike'], weakness: 'Radiant', loot: ['Shadow Fang', 'Fear Gland'] }, image_prompt: 'A nightmarish six-legged beast made of living shadow with glowing white eyes' },
    { name: 'Crystalback Tortoise', description: 'A colossal tortoise with a shell of living crystal that reflects magic.', metadata: { type: 'Beast', cr: 6, hp: 200, ac: 20, speed: '15ft', attacks: ['Crush', 'Crystal Barrage', 'Shell Reflect'], weakness: 'Sonic', loot: ['Crystal Shell Fragment', 'Prismatic Core'] }, image_prompt: 'An enormous tortoise with a magnificent crystalline shell reflecting rainbow light' },
    { name: 'Plague Wyvern', description: 'A diseased wyvern that spreads blight wherever it flies.', metadata: { type: 'Dragon', cr: 10, hp: 180, ac: 15, speed: '30ft/60ft fly', attacks: ['Toxic Bite', 'Blight Breath', 'Tail Sting'], weakness: 'Fire', loot: ['Plague Sac', 'Wyvern Wing Membrane'] }, image_prompt: 'A sickly green wyvern with rotting wings leaving a trail of toxic spores in the air' },
    { name: 'Iron Colossus', description: 'A towering construct left over from an ancient war, still following its last orders.', metadata: { type: 'Construct', cr: 14, hp: 300, ac: 22, speed: '30ft', attacks: ['Iron Fist', 'Beam Cannon', 'Stomp'], weakness: 'Lightning', loot: ['Colossus Core', 'Ancient Gears'] }, image_prompt: 'A massive rusted iron humanoid construct towering over buildings with glowing eyes' },
    { name: 'Dreamweaver Spider', description: 'A giant spider that traps victims in pleasant dreams while draining their life.', metadata: { type: 'Monstrosity', cr: 7, hp: 110, ac: 14, speed: '40ft/40ft climb', attacks: ['Dream Venom Bite', 'Web of Dreams', 'Psychic Drain'], weakness: 'Psychic', loot: ['Dreamsilk', 'Venom Sac'] }, image_prompt: 'A large iridescent spider spinning webs that shimmer with images of dreams' },
    { name: 'Ember Revenant', description: 'The fiery undead remains of a pyromancer who died in their own inferno.', metadata: { type: 'Undead', cr: 9, hp: 130, ac: 15, speed: '30ft', attacks: ['Ember Touch', 'Inferno Burst', 'Ashen Grasp'], weakness: 'Cold', loot: ['Eternal Ember', 'Charred Phylactery'] }, image_prompt: 'A skeletal figure wreathed in eternal flames with burning eye sockets' },
    { name: 'Tidecrusher Leviathan', description: 'A massive sea creature that can generate tsunamis with its tail.', metadata: { type: 'Beast', cr: 16, hp: 350, ac: 18, speed: '20ft/80ft swim', attacks: ['Crushing Jaws', 'Tsunami Tail', 'Whirlpool'], weakness: 'Lightning', loot: ['Leviathan Scale', 'Tidal Core'] }, image_prompt: 'A colossal whale-like creature with armored plates breaching the ocean surface' },
    { name: 'Mycelium Hivemind', description: 'A fungal network that has achieved sentience and controls infected creatures.', metadata: { type: 'Plant', cr: 11, hp: 160, ac: 12, speed: '5ft', attacks: ['Spore Cloud', 'Tendril Lash', 'Mind Control Spores'], weakness: 'Fire', loot: ['Hivemind Core', 'Sentient Spores'] }, image_prompt: 'A massive pulsating fungal mass with glowing neural network patterns and reaching tendrils' },
    { name: 'Sandstorm Djinn', description: 'A corrupted djinn made entirely of abrasive sand and wind.', metadata: { type: 'Elemental', cr: 12, hp: 170, ac: 17, speed: '30ft/60ft fly', attacks: ['Sand Blast', 'Whirlwind Form', 'Desiccate'], weakness: 'Water', loot: ['Djinn Essence', 'Sand Diamond'] }, image_prompt: 'A towering humanoid figure made of swirling sand with glowing amber eyes' },
    { name: 'Null Devourer', description: 'A creature from the space between planes that eats magic itself.', metadata: { type: 'Aberration', cr: 15, hp: 220, ac: 19, speed: '40ft/40ft fly', attacks: ['Mana Drain Bite', 'Null Field', 'Void Swallow'], weakness: 'Physical', loot: ['Null Fragment', 'Anti-Magic Gland'] }, image_prompt: 'A featureless black humanoid shape that distorts reality around it, eating light and color' },
    { name: 'Thornback Razorbeast', description: 'A territorial beast covered in razor-sharp thorns that it can launch.', metadata: { type: 'Beast', cr: 5, hp: 95, ac: 16, speed: '40ft', attacks: ['Gore', 'Thorn Volley', 'Charge'], weakness: 'Fire', loot: ['Razor Thorns', 'Thornback Hide'] }, image_prompt: 'A bear-sized beast covered in metallic thorns with a spiked tail and red eyes' },
    { name: 'Echomancer', description: 'A humanoid creature that can perfectly mimic any spell it has witnessed.', metadata: { type: 'Monstrosity', cr: 13, hp: 140, ac: 15, speed: '30ft', attacks: ['Mimic Spell', 'Echo Strike', 'Counterspell'], weakness: 'Silence', loot: ['Echo Crystal', 'Mimic Cortex'] }, image_prompt: 'A translucent humanoid figure that shimmers with echoes of different spells swirling around it' },
    { name: 'Bone Colosseum', description: 'A massive undead made from thousands of skeletons fused into one arena-shaped horror.', metadata: { type: 'Undead', cr: 18, hp: 400, ac: 20, speed: '20ft', attacks: ['Bone Storm', 'Skeleton Spawn', 'Crushing Arena'], weakness: 'Radiant', loot: ['Necrotic Core', 'Bone Dust'] }, image_prompt: 'A towering mass of fused skeletons forming a circular arena-like body with grabbing hands' },
    { name: 'Frostbloom Basilisk', description: 'A basilisk whose gaze freezes victims into ice sculptures instead of stone.', metadata: { type: 'Monstrosity', cr: 9, hp: 130, ac: 16, speed: '25ft', attacks: ['Freezing Gaze', 'Ice Fang Bite', 'Cold Breath'], weakness: 'Fire', loot: ['Frost Eye', 'Basilisk Scale'] }, image_prompt: 'A large reptilian creature with icy blue eyes and frost spreading from its gaze' },
    { name: 'Living Labyrinth', description: 'A dungeon that is itself a creature, reshaping its corridors to trap and digest prey.', metadata: { type: 'Aberration', cr: 20, hp: 500, ac: 18, speed: '0ft (immobile)', attacks: ['Wall Crush', 'Trap Corridor', 'Acid Floor', 'Mimic Door'], weakness: 'Earthquake', loot: ['Labyrinth Core', 'Dimensional Stone'] }, image_prompt: 'A twisting dungeon corridor where the walls have eyes and the floor ripples like flesh' },
  ],
  npcs: [
    { name: 'Merchant Zara', description: 'A charismatic traveling merchant who always has exactly what you need, at a price.', metadata: { role: 'Merchant', location: 'Traveling', disposition: 'Friendly', level: 5, services: ['Buy', 'Sell', 'Trade', 'Appraise'], faction: 'Trade Guild', quest_giver: true }, image_prompt: 'A smiling woman with a colorful wagon full of exotic wares and a mechanical parrot on her shoulder' },
    { name: 'Captain Holt Blacktide', description: 'A retired pirate captain who now runs a seedy tavern on the docks.', metadata: { role: 'Tavern Owner', location: 'Blacktide Tavern', disposition: 'Gruff but fair', level: 12, services: ['Rumors', 'Lodging', 'Drinks', 'Smuggling contacts'], faction: 'None', quest_giver: true }, image_prompt: 'A scarred man with a pegleg behind a bar counter with a mounted cutlass on the wall' },
    { name: 'Sage Elyndra', description: 'An ancient elven lorekeeper who guards forbidden knowledge in a crystal tower.', metadata: { role: 'Lorekeeper', location: 'Crystal Spire Library', disposition: 'Cautious', level: 18, services: ['Lore', 'Identify', 'Translation', 'Prophecy'], faction: 'Circle of Sages', quest_giver: true }, image_prompt: 'An ancient elf woman surrounded by floating books in a tower of crystal shelves' },
    { name: 'Grimjaw the Blacksmith', description: 'A half-orc smith who can forge weapons from any material, no matter how exotic.', metadata: { role: 'Blacksmith', location: 'Ironforge District', disposition: 'Business-like', level: 10, services: ['Forge', 'Repair', 'Enhance', 'Custom Orders'], faction: 'Smithing Guild', quest_giver: false }, image_prompt: 'A muscular half-orc hammering a glowing blade at an anvil surrounded by exotic weapons' },
    { name: 'Sister Mercy', description: 'A healer at the temple who asks no questions about how you got your wounds.', metadata: { role: 'Healer', location: 'Temple of the Dawn', disposition: 'Compassionate', level: 8, services: ['Heal', 'Cure Disease', 'Remove Curse', 'Resurrect'], faction: 'Temple of the Dawn', quest_giver: true }, image_prompt: 'A kind-faced woman in white robes with glowing hands tending to a wounded soldier' },
    { name: 'Whiskers', description: 'A talking cat who serves as the local thieves guild information broker.', metadata: { role: 'Information Broker', location: 'Alleyways', disposition: 'Sly', level: 6, services: ['Information', 'Rumors', 'Contacts', 'Blackmail'], faction: 'Shadow Network', quest_giver: true }, image_prompt: 'A sleek black cat with intelligent golden eyes sitting atop a stack of stolen documents' },
    { name: 'Magistrate Krevnor', description: 'The corrupt city magistrate who controls the courts with bribes and threats.', metadata: { role: 'Official', location: 'City Hall', disposition: 'Hostile (secretly)', level: 14, services: ['Legal Authority', 'Bounties', 'Pardons'], faction: 'City Government', quest_giver: true }, image_prompt: 'A thin man in expensive robes with cold calculating eyes sitting behind an imposing desk' },
    { name: 'Brokk Stonefist', description: 'An arena champion who trains adventurers in combat for a hefty fee.', metadata: { role: 'Trainer', location: 'Grand Arena', disposition: 'Competitive', level: 16, services: ['Combat Training', 'Sparring', 'Ability Training'], faction: 'Arena Guild', quest_giver: false }, image_prompt: 'A scarred dwarf in arena armor flexing in front of a cheering crowd' },
    { name: 'The Collector', description: 'A mysterious figure who buys rare and cursed artifacts, no questions asked.', metadata: { role: 'Buyer', location: 'Hidden Shop (changes location)', disposition: 'Mysterious', level: 20, services: ['Buy Rare Items', 'Buy Cursed Items', 'Special Commissions'], faction: 'Unknown', quest_giver: true }, image_prompt: 'A cloaked figure in a room full of glass cases containing bizarre and dangerous artifacts' },
    { name: 'Tilly Greenthumb', description: 'A cheerful gnome alchemist with a shop full of bubbling concoctions.', metadata: { role: 'Alchemist', location: 'Greenthumb Apothecary', disposition: 'Cheerful', level: 7, services: ['Potions', 'Poisons', 'Herbalism', 'Custom Brews'], faction: 'Alchemist Circle', quest_giver: true }, image_prompt: 'A bubbly gnome woman surrounded by colorful bubbling potions in a cramped shop' },
    { name: 'Herald Vox', description: 'A town crier and spy who knows everything happening in the city.', metadata: { role: 'Town Crier', location: 'Central Plaza', disposition: 'Talkative', level: 4, services: ['News', 'Rumors', 'Directions', 'Quest Board'], faction: 'City Government', quest_giver: true }, image_prompt: 'A lanky man with a huge bell and scroll standing on a crate shouting to passersby' },
    { name: 'Professor Cogsworth', description: 'An eccentric gnome professor who studies ancient constructs and wants field assistants.', metadata: { role: 'Scholar', location: 'University', disposition: 'Eccentric', level: 9, services: ['Knowledge', 'Construct Repair', 'Research'], faction: 'University', quest_giver: true }, image_prompt: 'A wild-haired gnome with multiple pairs of glasses surrounded by blueprints and tiny automatons' },
    { name: 'Mother Nightshade', description: 'A swamp hag who is surprisingly helpful if you bring her the right gifts.', metadata: { role: 'Witch', location: 'Darkwater Swamp', disposition: 'Unpredictable', level: 15, services: ['Hexes', 'Divination', 'Dark Potions', 'Forbidden Knowledge'], faction: 'Hag Coven', quest_giver: true }, image_prompt: 'A hunched old woman with green skin stirring a glowing cauldron in a swamp hut' },
    { name: 'Sir Reginald the Ghost', description: 'The ghost of a knight who haunts his old estate and offers quests to restore his honor.', metadata: { role: 'Quest Giver', location: 'Ruined Reginald Estate', disposition: 'Noble but sad', level: 10, services: ['Quests', 'Historical Knowledge', 'Haunting'], faction: 'None (deceased)', quest_giver: true }, image_prompt: 'A translucent knight in spectral armor standing in a decrepit mansion, looking mournful' },
    { name: 'Dockmaster Finn', description: 'A no-nonsense woman who controls all shipping in and out of the harbor.', metadata: { role: 'Official', location: 'Harbor', disposition: 'Stern', level: 6, services: ['Ship Passage', 'Cargo', 'Harbor Information', 'Ship Rental'], faction: 'Harbor Authority', quest_giver: true }, image_prompt: 'A weathered woman with a captain hat and clipboard standing on busy docks with ships behind her' },
  ],
  quests: [
    { name: 'The Dragon\'s Debt', description: 'A dragon owes a life debt to a farmer. Negotiate the terms before the dragon loses patience.', metadata: { type: 'Diplomacy', difficulty: 'Hard', level_range: '8-12', rewards: ['5000 gold', 'Dragon Scale Shield', 'Dragon Ally'], objectives: ['Meet the farmer', 'Speak with the dragon', 'Negotiate terms'], time_limit: '3 days', repeatable: false }, image_prompt: 'A massive dragon sitting across from a nervous farmer at a tiny table in a field' },
    { name: 'Plague of Shadows', description: 'Shadows are coming alive at night and dragging people into the darkness.', metadata: { type: 'Combat/Investigation', difficulty: 'Medium', level_range: '5-8', rewards: ['2000 gold', 'Shadowbane Amulet'], objectives: ['Investigate disappearances', 'Find the shadow source', 'Destroy the Shadow Nexus'], time_limit: 'None', repeatable: false }, image_prompt: 'Dark shadowy hands reaching out from walls and ground toward fleeing townspeople at night' },
    { name: 'The Alchemist\'s Last Brew', description: 'A dying alchemist needs rare ingredients for a potion that could save thousands.', metadata: { type: 'Fetch/Exploration', difficulty: 'Hard', level_range: '6-10', rewards: ['3000 gold', 'Master Alchemist Kit', 'Potion of Longevity'], objectives: ['Find Phoenix Tear', 'Harvest Abyssal Mushroom', 'Collect Unicorn Hair', 'Brew the potion'], time_limit: '7 days', repeatable: false }, image_prompt: 'An old alchemist on a cot pointing at a list of ingredients while coughing' },
    { name: 'Colosseum Champion', description: 'Fight through 10 rounds of increasingly dangerous arena combat for glory and gold.', metadata: { type: 'Combat', difficulty: 'Variable', level_range: '3-15', rewards: ['Progressive gold', 'Champion Title', 'Champion Belt'], objectives: ['Win Round 1-3: Beasts', 'Win Round 4-6: Warriors', 'Win Round 7-9: Monsters', 'Win Round 10: Champion'], time_limit: 'None', repeatable: true }, image_prompt: 'A gladiator standing victorious in a packed arena with defeated foes behind them' },
    { name: 'The Haunted Inheritance', description: 'You inherit a mansion, but it comes with a murderous ghost problem.', metadata: { type: 'Investigation/Combat', difficulty: 'Medium', level_range: '4-7', rewards: ['Mansion Property', '1500 gold', 'Ghost Lantern'], objectives: ['Explore the mansion', 'Discover the murder', 'Confront the ghost', 'Put the spirit to rest'], time_limit: 'None', repeatable: false }, image_prompt: 'A spooky Victorian mansion with ghostly figures visible in every window' },
    { name: 'Smuggler\'s Run', description: 'Transport illegal but life-saving medicine past a corrupt blockade.', metadata: { type: 'Stealth/Social', difficulty: 'Medium', level_range: '3-6', rewards: ['1000 gold', 'Smuggler Contacts', 'Reputation'], objectives: ['Obtain the medicine', 'Plan the route', 'Bypass the blockade', 'Deliver to the village'], time_limit: '2 days', repeatable: false }, image_prompt: 'A cloaked figure sneaking crates past guard towers at night on a moonlit road' },
    { name: 'The Living Dungeon', description: 'A dungeon has come alive and is growing, consuming the countryside.', metadata: { type: 'Dungeon Crawl', difficulty: 'Very Hard', level_range: '12-16', rewards: ['10000 gold', 'Dungeon Heart Crystal', 'Living Stone Armor'], objectives: ['Enter the living dungeon', 'Navigate shifting rooms', 'Find the Dungeon Heart', 'Destroy or tame it'], time_limit: 'Dungeon grows daily', repeatable: false }, image_prompt: 'A dungeon entrance that looks like a gaping mouth with stone teeth growing from the ground' },
    { name: 'Election Day', description: 'Help your chosen candidate win the mayoral election through fair means or foul.', metadata: { type: 'Social/Political', difficulty: 'Medium', level_range: '2-5', rewards: ['Political Favor', '800 gold', 'City Influence'], objectives: ['Choose a candidate', 'Campaign or sabotage', 'Debate prep', 'Survive election day'], time_limit: '5 days', repeatable: false }, image_prompt: 'Two rival politicians debating on a stage while shadowy figures scheme in the crowd' },
    { name: 'The Godstone Fragments', description: 'Collect five fragments of a shattered divine artifact before a cult reassembles it for dark purposes.', metadata: { type: 'Epic Quest', difficulty: 'Very Hard', level_range: '10-15', rewards: ['15000 gold', 'Godstone Blessing', 'Legendary Weapon Choice'], objectives: ['Find Fragment of Sky', 'Find Fragment of Sea', 'Find Fragment of Earth', 'Find Fragment of Flame', 'Find Fragment of Shadow', 'Prevent the ritual'], time_limit: '30 days', repeatable: false }, image_prompt: 'Five glowing stone fragments floating in a circle with cult members reaching for them' },
    { name: 'Monster Rancher', description: 'Capture, train, and battle monsters in the annual Monster Rancher Tournament.', metadata: { type: 'Collection/Combat', difficulty: 'Medium', level_range: '3-8', rewards: ['Tournament Prize (5000 gold)', 'Rare Monster Egg', 'Ranch Deed'], objectives: ['Capture 3 monsters', 'Train them', 'Win qualifier', 'Win tournament'], time_limit: '14 days', repeatable: true }, image_prompt: 'A trainer standing with three unique monsters in a tournament arena with crowds cheering' },
    { name: 'The Disappeared Village', description: 'An entire village vanished overnight. Only the buildings remain.', metadata: { type: 'Mystery', difficulty: 'Hard', level_range: '7-10', rewards: ['3500 gold', 'Phasing Cloak', 'Gratitude of survivors'], objectives: ['Investigate the village', 'Find the dimensional tear', 'Enter the mirror realm', 'Rescue villagers'], time_limit: 'None', repeatable: false }, image_prompt: 'An empty village with meals still on tables and a faint shimmer in the air' },
    { name: 'Brewing Storm', description: 'A storm giant king threatens war unless someone retrieves his stolen crown.', metadata: { type: 'Diplomacy/Heist', difficulty: 'Hard', level_range: '9-13', rewards: ['7000 gold', 'Storm Giant Alliance', 'Lightning Rod Staff'], objectives: ['Audience with the Storm King', 'Track the thief', 'Infiltrate the thief\'s fortress', 'Return the crown'], time_limit: '10 days', repeatable: false }, image_prompt: 'A massive storm giant on a throne of clouds looking down angrily at tiny adventurers' },
    { name: 'The Endless Feast', description: 'A magical feast appears in town that no one can stop eating. Find the source before everyone starves from magical food.', metadata: { type: 'Investigation', difficulty: 'Medium', level_range: '4-7', rewards: ['2000 gold', 'Cornucopia of Plenty', 'Town Hero status'], objectives: ['Resist the feast', 'Investigate the food source', 'Find the fey responsible', 'Break the enchantment'], time_limit: '3 days', repeatable: false }, image_prompt: 'Townspeople mindlessly gorging at long magical tables while enchanted food keeps appearing' },
    { name: 'Clockwork Uprising', description: 'The automatons in the Clockwork Foundry have gained sentience and demand rights.', metadata: { type: 'Diplomacy/Combat', difficulty: 'Hard', level_range: '8-12', rewards: ['4000 gold', 'Automaton Companion', 'Clockwork Prosthetic'], objectives: ['Investigate the awakening', 'Choose a side', 'Negotiate or fight', 'Determine the fate of constructs'], time_limit: 'None', repeatable: false }, image_prompt: 'Intelligent clockwork automatons holding protest signs outside a factory while guards watch' },
    { name: 'The Memory Thief', description: 'Someone is stealing memories from townspeople, leaving them as empty shells.', metadata: { type: 'Investigation/Combat', difficulty: 'Hard', level_range: '7-11', rewards: ['3000 gold', 'Memory Crystal', 'Mindshield Circlet'], objectives: ['Interview victims', 'Track the psychic trail', 'Confront the Memory Thief', 'Restore stolen memories'], time_limit: '5 days', repeatable: false }, image_prompt: 'A sinister cloaked figure extracting glowing wisps from a sleeping person\'s head' },
  ],
  spells: [
    { name: 'Graviton Collapse', description: 'Creates a point of intense gravity that pulls everything inward.', metadata: { school: 'Transmutation', level: 7, casting_time: '1 action', range: '120ft', duration: 'Concentration, 1 minute', damage: '6d10 force', components: 'V, S, M (a lodestone)', aoe: '30ft sphere' }, image_prompt: 'A dark sphere of crushing gravity pulling in rocks, debris and enemies' },
    { name: 'Healing Rain', description: 'Summons a warm rain that heals all allies in the area over time.', metadata: { school: 'Evocation', level: 4, casting_time: '1 action', range: '60ft', duration: '1 minute', damage: 'Heals 2d6 per round', components: 'V, S', aoe: '40ft radius' }, image_prompt: 'Warm golden rain falling from a small cloud, healing wounds of warriors below' },
    { name: 'Mirror Legion', description: 'Creates illusory duplicates that fight alongside the caster.', metadata: { school: 'Illusion', level: 5, casting_time: '1 action', range: 'Self', duration: '10 minutes', damage: 'Duplicates deal 1d8 each', components: 'V, S, M (a shard of mirror)', aoe: 'Self', summons: 4 }, image_prompt: 'A wizard surrounded by four identical mirror copies all casting spells in unison' },
    { name: 'Soul Siphon', description: 'Drains life force from a target, transferring it to the caster.', metadata: { school: 'Necromancy', level: 6, casting_time: '1 action', range: '60ft', duration: 'Instantaneous', damage: '8d6 necrotic (heals half)', components: 'V, S', aoe: 'Single target' }, image_prompt: 'A stream of ghostly white energy flowing from a victim to a dark mage\'s outstretched hand' },
    { name: 'Chrono Stutter', description: 'Briefly loops time for one target, making them repeat their last action.', metadata: { school: 'Chronomancy', level: 5, casting_time: '1 reaction', range: '60ft', duration: 'Instantaneous', damage: 'None (control)', components: 'V, S', aoe: 'Single target', save: 'Wisdom' }, image_prompt: 'A creature caught in a golden time loop, repeating the same motion over and over' },
    { name: 'Magma Geyser', description: 'Erupts a column of magma from the ground beneath enemies.', metadata: { school: 'Evocation', level: 5, casting_time: '1 action', range: '90ft', duration: 'Instantaneous', damage: '6d8 fire + 2d8 bludgeoning', components: 'V, S, M (volcanic rock)', aoe: '15ft cylinder' }, image_prompt: 'A violent eruption of magma bursting from cracked earth beneath enemies' },
    { name: 'Phantom Orchestra', description: 'Summons ghostly musicians whose music buffs allies and debuffs enemies.', metadata: { school: 'Enchantment', level: 3, casting_time: '1 action', range: '60ft', duration: 'Concentration, 10 minutes', damage: 'None (buff/debuff)', components: 'V, S, M (a tuning fork)', aoe: '30ft radius', effect: '+2 allies, -2 enemies to attacks' }, image_prompt: 'Translucent ghostly musicians playing instruments with visible sound waves affecting a battlefield' },
    { name: 'Thornwall Fortress', description: 'Raises a massive wall of thorny vines that damages those who try to pass.', metadata: { school: 'Conjuration', level: 4, casting_time: '1 action', range: '120ft', duration: '10 minutes', damage: '4d6 piercing to those passing through', components: 'V, S, M (a thorn)', aoe: '60ft long, 10ft high, 5ft thick' }, image_prompt: 'A massive wall of twisted thorny vines erupting from the ground blocking a pass' },
    { name: 'Arcane Satellite', description: 'Launches a glowing orb into the sky that rains down arcane bolts each round.', metadata: { school: 'Evocation', level: 6, casting_time: '1 action', range: '300ft', duration: 'Concentration, 1 minute', damage: '3d6 force per bolt, 3 bolts per round', components: 'V, S, M (a star sapphire)', aoe: '100ft radius from satellite' }, image_prompt: 'A glowing arcane orb hovering high above a battlefield raining down beams of force energy' },
    { name: 'Flesh to Crystal', description: 'Slowly transforms a creature into living crystal, immobilizing them.', metadata: { school: 'Transmutation', level: 6, casting_time: '1 action', range: '60ft', duration: 'Permanent (reversible)', damage: 'None (petrification variant)', components: 'V, S, M (quartz shard)', aoe: 'Single target', save: 'Constitution' }, image_prompt: 'A creature mid-transformation as their body turns from flesh to sparkling crystal' },
    { name: 'Void Step', description: 'Teleport through the void between planes, appearing behind your target.', metadata: { school: 'Conjuration', level: 3, casting_time: '1 bonus action', range: '60ft', duration: 'Instantaneous', damage: 'None (teleport) + advantage on next attack', components: 'V', aoe: 'Self' }, image_prompt: 'A figure stepping into a dark tear in reality and emerging from another behind an enemy' },
    { name: 'Bloodfire Curse', description: 'Ignites the blood of a target, dealing fire damage from within.', metadata: { school: 'Necromancy', level: 4, casting_time: '1 action', range: '30ft', duration: '3 rounds', damage: '3d8 fire per round', components: 'V, S', aoe: 'Single target', save: 'Constitution' }, image_prompt: 'A screaming figure with glowing red veins as their blood burns from within' },
    { name: 'Nature\'s Embrace', description: 'Wraps the caster in living bark and leaves, granting armor and regeneration.', metadata: { school: 'Transmutation', level: 3, casting_time: '1 bonus action', range: 'Self', duration: '1 hour', damage: 'None (+4 AC, regenerate 1d4/round)', components: 'V, S, M (a leaf)', aoe: 'Self' }, image_prompt: 'A druid covered in living bark armor with green leaves and vines growing over them' },
    { name: 'Dimensional Anchor', description: 'Prevents all teleportation and planar travel in an area.', metadata: { school: 'Abjuration', level: 4, casting_time: '1 action', range: '120ft', duration: '1 hour', damage: 'None (anti-teleport)', components: 'V, S, M (iron chain link)', aoe: '60ft radius' }, image_prompt: 'Glowing golden chains anchoring reality in place preventing dimensional travel in an area' },
    { name: 'Prismatic Barrage', description: 'Fires seven beams of different-colored energy, each with a unique effect.', metadata: { school: 'Evocation', level: 8, casting_time: '1 action', range: '120ft', duration: 'Instantaneous', damage: 'Variable per beam (fire, cold, lightning, poison, acid, force, psychic)', components: 'V, S', aoe: '7 beams, single or multiple targets' }, image_prompt: 'Seven brilliant beams of rainbow colors firing from a wizard\'s hands at enemies' },
  ],
  armor: [
    { name: 'Dragonscale Platemail', description: 'Armor forged from the scales of a red dragon, radiating heat.', metadata: { type: 'Heavy', ac_bonus: 8, weight: 45, rarity: 'Legendary', element_resistance: 'Fire Immunity', slot: 'Chest', strength_req: 18, stealth_disadvantage: true }, image_prompt: 'Imposing red-scaled plate armor with a faint heat shimmer radiating from it' },
    { name: 'Wraithweave Cloak', description: 'A cloak woven from ectoplasm that makes the wearer partially incorporeal.', metadata: { type: 'Light', ac_bonus: 3, weight: 1, rarity: 'Very Rare', element_resistance: 'Necrotic 50%', slot: 'Cloak', strength_req: 0, special: '20% miss chance from physical attacks' }, image_prompt: 'A flowing translucent cloak that makes the wearer appear ghostly and semi-transparent' },
    { name: 'Ironbark Cuirass', description: 'Druidic armor grown from living ironwood, as strong as steel but alive.', metadata: { type: 'Medium', ac_bonus: 6, weight: 20, rarity: 'Rare', element_resistance: 'Poison', slot: 'Chest', strength_req: 12, special: 'Can be worn by druids' }, image_prompt: 'A cuirass made of dark living wood with small green leaves still growing from it' },
    { name: 'Stormguard Shield', description: 'A tower shield that absorbs lightning and can release it as a counterattack.', metadata: { type: 'Shield', ac_bonus: 3, weight: 12, rarity: 'Rare', element_resistance: 'Lightning Immunity', slot: 'Off-hand', strength_req: 15, special: 'Absorb and redirect lightning' }, image_prompt: 'A large metal tower shield crackling with stored electrical energy' },
    { name: 'Abyssal Chain Shirt', description: 'Chainmail forged in the Abyss that whispers dark secrets to the wearer.', metadata: { type: 'Medium', ac_bonus: 5, weight: 25, rarity: 'Very Rare', element_resistance: 'Psychic', slot: 'Chest', strength_req: 13, special: '+2 Intimidation, -1 Sanity per day', cursed: true }, image_prompt: 'Dark chainmail with links that seem to move on their own and faint screaming faces' },
    { name: 'Celestial Helm', description: 'A helm blessed by angels that grants divine sight and protection from evil.', metadata: { type: 'Helm', ac_bonus: 2, weight: 4, rarity: 'Very Rare', element_resistance: 'Radiant', slot: 'Head', strength_req: 0, special: 'Truesight 30ft, Protection from Evil' }, image_prompt: 'A gleaming golden helm with a halo-like crest and wings on the sides' },
    { name: 'Frostforged Gauntlets', description: 'Gauntlets that freeze the air around the wearer\'s hands, adding cold damage to strikes.', metadata: { type: 'Gauntlets', ac_bonus: 1, weight: 3, rarity: 'Uncommon', element_resistance: 'Cold 25%', slot: 'Hands', strength_req: 10, special: '+1d4 cold damage to unarmed/melee' }, image_prompt: 'Metal gauntlets covered in a layer of frost with icy mist flowing from the fingers' },
    { name: 'Spidersilk Bodysuit', description: 'A nearly invisible suit of armor woven from giant spider silk.', metadata: { type: 'Light', ac_bonus: 4, weight: 3, rarity: 'Rare', element_resistance: 'None', slot: 'Full Body', strength_req: 0, special: 'No stealth penalty, +2 Acrobatics, can be worn under clothing' }, image_prompt: 'A form-fitting translucent bodysuit with a faint web pattern visible in certain light' },
    { name: 'Volcanic Greaves', description: 'Leg armor forged in a volcano that leaves burning footprints.', metadata: { type: 'Heavy', ac_bonus: 2, weight: 8, rarity: 'Uncommon', element_resistance: 'Fire 25%', slot: 'Legs', strength_req: 14, special: 'Burning footprints deal 1d4 fire to followers' }, image_prompt: 'Dark metal leg armor with glowing orange cracks like cooling lava leaving fiery footprints' },
    { name: 'Dreamcatcher Mantle', description: 'A feathered mantle that protects the mind during sleep and waking.', metadata: { type: 'Light', ac_bonus: 2, weight: 2, rarity: 'Rare', element_resistance: 'Psychic Immunity', slot: 'Shoulders', strength_req: 0, special: 'Immune to sleep effects and dream manipulation' }, image_prompt: 'A feathered shoulder mantle with small dreamcatchers woven in that glow faintly blue' },
    { name: 'Golem Plate', description: 'Armor taken from a destroyed iron golem and reshaped for humanoid use.', metadata: { type: 'Heavy', ac_bonus: 9, weight: 65, rarity: 'Very Rare', element_resistance: 'Magic Resistance', slot: 'Full Body', strength_req: 20, stealth_disadvantage: true, special: 'Speed reduced by 10ft' }, image_prompt: 'Massive thick iron plate armor with visible golem runes still glowing on its surface' },
    { name: 'Tideturner Buckler', description: 'A small shield made from a giant clamshell that controls water.', metadata: { type: 'Shield', ac_bonus: 2, weight: 4, rarity: 'Rare', element_resistance: 'Cold 50%', slot: 'Off-hand', strength_req: 10, special: 'Control Water at will within 30ft' }, image_prompt: 'A pearlescent shield made from a giant clamshell with water swirling around it' },
    { name: 'Shadowstep Boots', description: 'Boots that allow the wearer to teleport between shadows.', metadata: { type: 'Boots', ac_bonus: 1, weight: 2, rarity: 'Very Rare', element_resistance: 'None', slot: 'Feet', strength_req: 0, special: 'Shadow teleport 60ft, 3/day' }, image_prompt: 'Sleek black leather boots that dissolve into shadow at the edges' },
    { name: 'Living Vine Armor', description: 'Armor that is a symbiotic plant organism, it grows stronger as you fight.', metadata: { type: 'Medium', ac_bonus: 5, weight: 15, rarity: 'Rare', element_resistance: 'Poison', slot: 'Chest', strength_req: 10, special: 'AC increases by +1 per combat round (max +3)' }, image_prompt: 'Green vine armor covering a warrior that visibly grows and thickens during combat' },
    { name: 'Astral Plate', description: 'Armor made from solidified astral energy, nearly weightless and otherworldly.', metadata: { type: 'Heavy', ac_bonus: 8, weight: 5, rarity: 'Legendary', element_resistance: 'Force', slot: 'Full Body', strength_req: 10, special: 'No weight, no stealth penalty, can phase through walls 1/day' }, image_prompt: 'Ethereal glowing plate armor that seems to float on the wearer with stars visible in its surface' },
  ],
  vehicles: [
    { name: 'Skycutter Glider', description: 'A lightweight magical glider that rides ley line currents.', metadata: { type: 'Air', speed: '80 mph', capacity: 1, fuel: 'Ley line energy', hp: 40, ac: 12, special: 'Silent flight, no fuel cost on ley lines' }, image_prompt: 'A sleek crystalline hang glider trailing magical energy as it soars through clouds' },
    { name: 'Iron Tortoise Tank', description: 'A slow but nearly indestructible dwarven siege vehicle.', metadata: { type: 'Land', speed: '10 mph', capacity: 8, fuel: 'Steam/Coal', hp: 300, ac: 22, special: 'Cannon turret, battering ram', weapons: ['Main Cannon', 'Flamethrower'] }, image_prompt: 'A massive steam-powered tortoise-shaped tank with a cannon on top and iron plating' },
    { name: 'Waveskimmer Catamaran', description: 'A swift dual-hulled sailing vessel enchanted to skim above the water surface.', metadata: { type: 'Sea', speed: '40 knots', capacity: 12, fuel: 'Wind/Magic', hp: 120, ac: 14, special: 'Hovers above water, immune to sea monsters' }, image_prompt: 'A sleek catamaran hovering just above ocean waves with glowing hull runes' },
    { name: 'Burrower Mole Machine', description: 'A gnomish drilling machine that tunnels through earth and rock.', metadata: { type: 'Underground', speed: '15 mph (dirt), 5 mph (rock)', capacity: 4, fuel: 'Elemental fire core', hp: 180, ac: 18, special: 'Tunnels through any material, sealed cabin' }, image_prompt: 'A brass cylindrical drilling machine with a giant rotating drill bit emerging from the ground' },
    { name: 'Phantom Carriage', description: 'A ghostly horse-drawn carriage that can pass through walls and travel the ethereal plane.', metadata: { type: 'Ethereal', speed: '60 mph', capacity: 4, fuel: 'Soul gems', hp: 80, ac: 16, special: 'Ethereal travel, pass through objects, undead horses' }, image_prompt: 'A translucent ghostly black carriage pulled by spectral horses phasing through a wall' },
    { name: 'Magma Surfer', description: 'A heatproof board designed for riding magma flows inside volcanoes.', metadata: { type: 'Lava', speed: '30 mph', capacity: 1, fuel: 'Self-sustaining', hp: 60, ac: 15, special: 'Fire immunity, can ride any lava flow' }, image_prompt: 'A glowing obsidian surfboard riding a river of bright orange lava inside a volcano' },
    { name: 'Cloudship Nimbus', description: 'A massive airship made from solidified clouds, armed with lightning cannons.', metadata: { type: 'Air', speed: '50 mph', capacity: 50, fuel: 'Storm essence', hp: 400, ac: 16, special: 'Lightning cannons, cloud camouflage', weapons: ['Lightning Cannons x4', 'Wind Blast'] }, image_prompt: 'A grand ship made of clouds with lightning crackling between its masts and billowing sails' },
    { name: 'Sand Strider', description: 'A six-legged mechanical walker designed for desert traversal.', metadata: { type: 'Land', speed: '35 mph', capacity: 6, fuel: 'Solar crystals', hp: 150, ac: 16, special: 'All-terrain desert, solar powered, storage compartment' }, image_prompt: 'A six-legged brass mechanical walker striding across sand dunes with a cabin on top' },
    { name: 'Leviathan Submarine', description: 'A whale-shaped submarine that can dive to ocean floor depths.', metadata: { type: 'Underwater', speed: '25 knots', capacity: 20, fuel: 'Water elemental core', hp: 250, ac: 18, special: 'Deep sea capable, sonar, torpedo tubes', weapons: ['Torpedoes x6'] }, image_prompt: 'A massive whale-shaped metal submarine with portholes and propellers diving deep underwater' },
    { name: 'Treestride Canoe', description: 'A living wooden canoe that can travel between trees using tree stride magic.', metadata: { type: 'Land/Water', speed: '15 mph (water), instant (tree teleport)', capacity: 3, fuel: 'Druidic blessing', hp: 50, ac: 12, special: 'Teleport between large trees within 1 mile' }, image_prompt: 'A canoe made of living wood with leaves, emerging from inside the trunk of a massive tree' },
    { name: 'Warp Sled', description: 'A gravity-defying sled that tears through space at incredible speeds.', metadata: { type: 'Multi-dimensional', speed: '200 mph', capacity: 2, fuel: 'Void crystals', hp: 60, ac: 14, special: 'Short-range teleportation, leaves afterimages' }, image_prompt: 'A sleek metallic sled leaving purple afterimages as it warps through space above a road' },
    { name: 'Golem Palanquin', description: 'A luxurious chair carried by four tireless stone golems.', metadata: { type: 'Land', speed: '20 mph', capacity: 2, fuel: 'Enchantment (permanent)', hp: 200, ac: 17, special: 'Golems fight to protect passengers, never tires' }, image_prompt: 'An ornate golden chair being carried by four stone golems marching in perfect unison' },
    { name: 'Stormrider Chariot', description: 'A chariot pulled by lightning elementals that rides on thunderclouds.', metadata: { type: 'Air', speed: '120 mph', capacity: 2, fuel: 'Lightning essence', hp: 100, ac: 15, special: 'Can call storms, lightning bolt attack', weapons: ['Lightning Bolt'] }, image_prompt: 'A golden chariot pulled by beings of pure lightning riding on a dark thundercloud' },
    { name: 'Coral Crawler', description: 'A living coral construct that walks on the ocean floor.', metadata: { type: 'Underwater', speed: '10 mph', capacity: 6, fuel: 'Self-sustaining (living)', hp: 200, ac: 19, special: 'Air bubble interior, regenerates 10 hp/round, grows over time' }, image_prompt: 'A crab-like construct made of colorful living coral walking on the ocean floor with a bubble cabin' },
    { name: 'Pocket Zeppelin', description: 'A personal one-person airship that folds into a backpack when not in use.', metadata: { type: 'Air', speed: '30 mph', capacity: 1, fuel: 'Helium crystals', hp: 30, ac: 10, special: 'Folds to portable size, quiet, low profile' }, image_prompt: 'A tiny personal blimp with a single seat basket, just big enough for one person' },
  ],
  sound_effects: [
    { name: 'Thunder Crack', description: 'A massive thunderclap that shakes the screen, used for powerful spell impacts.', metadata: { category: 'Combat', duration: '2.1s', format: 'WAV', sample_rate: 48000, channels: 'Stereo', tags: ['thunder', 'impact', 'spell', 'explosion'], intensity: 'High' }, image_prompt: 'Visual representation of a massive sound wave from a lightning strike' },
    { name: 'Ethereal Whispers', description: 'Ghostly whispering voices for haunted areas and necromantic effects.', metadata: { category: 'Ambient', duration: '8.0s', format: 'WAV', sample_rate: 48000, channels: 'Stereo', tags: ['ghost', 'whisper', 'haunted', 'eerie'], intensity: 'Low', loopable: true }, image_prompt: 'Translucent ghostly mouths whispering in a dark corridor' },
    { name: 'Sword Clash', description: 'Metal on metal sword clash with reverb for arena combat.', metadata: { category: 'Combat', duration: '0.8s', format: 'WAV', sample_rate: 48000, channels: 'Stereo', tags: ['sword', 'metal', 'combat', 'clash'], intensity: 'Medium' }, image_prompt: 'Two swords clashing with sparks flying at the point of contact' },
    { name: 'Healing Chime', description: 'A warm crystalline chime sound for healing spells and health restoration.', metadata: { category: 'UI/Magic', duration: '1.5s', format: 'WAV', sample_rate: 48000, channels: 'Stereo', tags: ['heal', 'chime', 'positive', 'magic'], intensity: 'Low' }, image_prompt: 'Golden sparkles rising with visible warm sound waves emanating from a crystal' },
    { name: 'Dragon Roar', description: 'A terrifying dragon roar that reverberates through the environment.', metadata: { category: 'Creature', duration: '3.5s', format: 'WAV', sample_rate: 48000, channels: 'Stereo', tags: ['dragon', 'roar', 'monster', 'terrifying'], intensity: 'Very High' }, image_prompt: 'A dragon with open jaws releasing a visible shockwave of sound' },
    { name: 'Campfire Crackle', description: 'Comforting campfire crackling for rest scenes and camp menus.', metadata: { category: 'Ambient', duration: '15.0s', format: 'WAV', sample_rate: 48000, channels: 'Stereo', tags: ['fire', 'campfire', 'rest', 'cozy'], intensity: 'Low', loopable: true }, image_prompt: 'A warm campfire with visible crackling embers floating upward at night' },
    { name: 'Portal Opening', description: 'A swirling energy sound for teleportation and portal effects.', metadata: { category: 'Magic', duration: '2.5s', format: 'WAV', sample_rate: 48000, channels: 'Stereo', tags: ['portal', 'teleport', 'energy', 'whoosh'], intensity: 'Medium' }, image_prompt: 'A swirling magical portal opening with energy spiraling inward' },
    { name: 'Coin Pouch Jingle', description: 'The satisfying sound of coins jingling when looting or trading.', metadata: { category: 'UI', duration: '0.6s', format: 'WAV', sample_rate: 44100, channels: 'Mono', tags: ['coins', 'loot', 'money', 'reward'], intensity: 'Low' }, image_prompt: 'Gold coins spilling from a leather pouch onto a wooden table' },
    { name: 'Ice Shatter', description: 'Dramatic ice shattering for frost spells and frozen enemy breaks.', metadata: { category: 'Combat/Magic', duration: '1.8s', format: 'WAV', sample_rate: 48000, channels: 'Stereo', tags: ['ice', 'shatter', 'frost', 'break'], intensity: 'High' }, image_prompt: 'A frozen figure shattering into thousands of ice fragments' },
    { name: 'Dungeon Door Creak', description: 'An ominous heavy door creaking open in a dungeon setting.', metadata: { category: 'Environment', duration: '3.0s', format: 'WAV', sample_rate: 48000, channels: 'Stereo', tags: ['door', 'creak', 'dungeon', 'ominous'], intensity: 'Medium' }, image_prompt: 'A massive iron-bound wooden door creaking open revealing darkness beyond' },
    { name: 'Level Up Fanfare', description: 'A triumphant musical sting for player level-up moments.', metadata: { category: 'UI', duration: '2.0s', format: 'WAV', sample_rate: 48000, channels: 'Stereo', tags: ['levelup', 'fanfare', 'achievement', 'triumphant'], intensity: 'Medium' }, image_prompt: 'A burst of golden light and stars erupting upward with energy' },
    { name: 'Arrow Whizz', description: 'The sound of an arrow flying past the camera at high speed.', metadata: { category: 'Combat', duration: '0.5s', format: 'WAV', sample_rate: 48000, channels: 'Stereo', tags: ['arrow', 'projectile', 'whizz', 'fast'], intensity: 'Medium' }, image_prompt: 'An arrow streaking through the air with motion blur' },
    { name: 'Underwater Ambience', description: 'Muffled underwater sounds with distant whale calls for ocean levels.', metadata: { category: 'Ambient', duration: '20.0s', format: 'WAV', sample_rate: 48000, channels: 'Stereo', tags: ['underwater', 'ocean', 'whale', 'ambient'], intensity: 'Low', loopable: true }, image_prompt: 'Deep blue underwater scene with bubbles and distant light from above' },
    { name: 'Explosion Boom', description: 'A massive explosion with debris for destructible environments and big spells.', metadata: { category: 'Combat', duration: '3.0s', format: 'WAV', sample_rate: 48000, channels: 'Stereo', tags: ['explosion', 'boom', 'destruction', 'impact'], intensity: 'Very High' }, image_prompt: 'A massive fiery explosion sending debris and shockwaves outward' },
    { name: 'Mystical Hum', description: 'A low resonant hum for ancient artifacts and magical locations.', metadata: { category: 'Ambient/Magic', duration: '10.0s', format: 'WAV', sample_rate: 48000, channels: 'Stereo', tags: ['mystical', 'hum', 'artifact', 'ancient'], intensity: 'Low', loopable: true }, image_prompt: 'An ancient glowing artifact vibrating with visible mystical energy waves' },
  ],
  textures: [
    { name: 'Cracked Lava Stone', description: 'Dark volcanic rock with glowing lava visible through deep cracks.', metadata: { resolution: '2048x2048', format: 'PNG', tileable: true, category: 'Ground', maps: ['Diffuse', 'Normal', 'Emissive', 'Roughness'], style: 'Realistic', pbr: true }, image_prompt: 'Tileable texture of dark cracked stone with bright orange lava glowing through cracks' },
    { name: 'Ancient Brick Wall', description: 'Weathered stone bricks with moss growing in the mortar lines.', metadata: { resolution: '2048x2048', format: 'PNG', tileable: true, category: 'Wall', maps: ['Diffuse', 'Normal', 'AO', 'Roughness'], style: 'Realistic', pbr: true }, image_prompt: 'Tileable texture of old grey stone bricks with green moss in the cracks' },
    { name: 'Enchanted Wood Planks', description: 'Wooden planks with faintly glowing magical runes carved into them.', metadata: { resolution: '2048x2048', format: 'PNG', tileable: true, category: 'Floor', maps: ['Diffuse', 'Normal', 'Emissive', 'Roughness'], style: 'Stylized', pbr: true }, image_prompt: 'Tileable wooden plank texture with faint blue glowing runes carved in the grain' },
    { name: 'Crystal Cave Surface', description: 'A surface studded with reflective crystal formations of various sizes.', metadata: { resolution: '4096x4096', format: 'PNG', tileable: true, category: 'Cave Wall', maps: ['Diffuse', 'Normal', 'Metallic', 'Roughness', 'Emissive'], style: 'Realistic', pbr: true }, image_prompt: 'Tileable cave wall texture covered in reflective colorful crystal formations' },
    { name: 'Dragon Scale Pattern', description: 'Overlapping dragon scales in deep red with subtle iridescence.', metadata: { resolution: '2048x2048', format: 'PNG', tileable: true, category: 'Creature', maps: ['Diffuse', 'Normal', 'Roughness', 'Metallic'], style: 'Realistic', pbr: true }, image_prompt: 'Tileable pattern of overlapping red dragon scales with iridescent sheen' },
    { name: 'Frozen Tundra Ground', description: 'Cracked frozen earth with patches of ice and snow.', metadata: { resolution: '2048x2048', format: 'PNG', tileable: true, category: 'Ground', maps: ['Diffuse', 'Normal', 'Roughness', 'AO'], style: 'Realistic', pbr: true }, image_prompt: 'Tileable frozen ground texture with cracked ice, snow patches, and frozen dirt' },
    { name: 'Steampunk Metal Plate', description: 'Riveted brass and copper metal plates with gear patterns.', metadata: { resolution: '2048x2048', format: 'PNG', tileable: true, category: 'Metal', maps: ['Diffuse', 'Normal', 'Metallic', 'Roughness'], style: 'Stylized', pbr: true }, image_prompt: 'Tileable brass metal plate texture with rivets and embossed gear patterns' },
    { name: 'Ghostly Marble', description: 'White marble with translucent ghostly wisps visible inside.', metadata: { resolution: '2048x2048', format: 'PNG', tileable: true, category: 'Floor', maps: ['Diffuse', 'Normal', 'Roughness', 'Subsurface'], style: 'Fantasy', pbr: true }, image_prompt: 'Tileable white marble texture with ghostly translucent wisps trapped inside the stone' },
    { name: 'Mushroom Cap Surface', description: 'The spotted top surface of a giant fantasy mushroom.', metadata: { resolution: '2048x2048', format: 'PNG', tileable: true, category: 'Organic', maps: ['Diffuse', 'Normal', 'Roughness', 'Subsurface'], style: 'Stylized', pbr: true }, image_prompt: 'Tileable texture of a giant mushroom cap surface with colorful spots and soft texture' },
    { name: 'Necrotic Flesh', description: 'Undead skin texture with visible veins, stitches, and decay.', metadata: { resolution: '2048x2048', format: 'PNG', tileable: true, category: 'Creature', maps: ['Diffuse', 'Normal', 'Roughness', 'Subsurface'], style: 'Realistic', pbr: true }, image_prompt: 'Tileable undead flesh texture with visible dark veins, stitches, and patches of decay' },
    { name: 'Sand Dune Ripples', description: 'Wind-swept desert sand with fine ripple patterns.', metadata: { resolution: '2048x2048', format: 'PNG', tileable: true, category: 'Ground', maps: ['Diffuse', 'Normal', 'Roughness', 'Displacement'], style: 'Realistic', pbr: true }, image_prompt: 'Tileable golden sand texture with fine wind-swept ripple patterns' },
    { name: 'Arcane Circuit Board', description: 'A magical surface that looks like a circuit board made of runes and ley lines.', metadata: { resolution: '2048x2048', format: 'PNG', tileable: true, category: 'Sci-Fantasy', maps: ['Diffuse', 'Normal', 'Emissive', 'Roughness'], style: 'Stylized', pbr: true }, image_prompt: 'Tileable texture resembling a circuit board but made of glowing magical runes and golden ley lines' },
    { name: 'Coral Reef Surface', description: 'Colorful coral reef texture with small sea life details.', metadata: { resolution: '4096x4096', format: 'PNG', tileable: true, category: 'Underwater', maps: ['Diffuse', 'Normal', 'Roughness', 'AO'], style: 'Realistic', pbr: true }, image_prompt: 'Tileable colorful coral reef texture with tiny sea creatures and plant details' },
    { name: 'Dark Iron Grate', description: 'Industrial iron grate with gaps showing darkness below.', metadata: { resolution: '2048x2048', format: 'PNG', tileable: true, category: 'Metal/Industrial', maps: ['Diffuse', 'Normal', 'Metallic', 'Roughness', 'Alpha'], style: 'Realistic', pbr: true }, image_prompt: 'Tileable dark iron grate texture with gaps revealing darkness below' },
    { name: 'Elven Silk Fabric', description: 'Luxurious flowing silk with subtle elven vine patterns woven in.', metadata: { resolution: '2048x2048', format: 'PNG', tileable: true, category: 'Fabric', maps: ['Diffuse', 'Normal', 'Roughness'], style: 'Fantasy', pbr: true }, image_prompt: 'Tileable silky fabric texture in deep blue with subtle golden elven vine patterns woven in' },
  ],
  ui_elements: [
    { name: 'Health Orb', description: 'A glass orb filled with red liquid that drains as health decreases.', metadata: { type: 'HUD', category: 'Health Display', resolution: '256x256', format: 'PNG', animated: true, states: ['Full', 'High', 'Medium', 'Low', 'Critical', 'Empty'], style: 'Fantasy' }, image_prompt: 'A glass orb filled with glowing red liquid at various fill levels for health display' },
    { name: 'Minimap Frame', description: 'An ornate circular minimap border with cardinal direction markers.', metadata: { type: 'HUD', category: 'Navigation', resolution: '300x300', format: 'PNG', animated: false, style: 'Medieval Fantasy', features: ['Compass Rose', 'Quest Markers', 'Player Arrow'] }, image_prompt: 'An ornate golden circular frame for a minimap with compass directions and decorative filigree' },
    { name: 'Inventory Slot', description: 'A single inventory slot with a subtle glow effect for item rarity.', metadata: { type: 'Menu', category: 'Inventory', resolution: '64x64', format: 'PNG', animated: false, variants: ['Empty', 'Common', 'Uncommon', 'Rare', 'Epic', 'Legendary'], style: 'Fantasy' }, image_prompt: 'A set of inventory slot frames with different colored borders for item rarity levels' },
    { name: 'Dialogue Box', description: 'A parchment-style dialogue box with character portrait frame.', metadata: { type: 'Dialogue', category: 'Social', resolution: '800x200', format: 'PNG + 9-slice', animated: false, features: ['Portrait Frame', 'Name Plate', 'Text Area', 'Continue Arrow'], style: 'Parchment' }, image_prompt: 'A parchment-style dialogue box with a character portrait area on the left and text area' },
    { name: 'Action Bar', description: 'A horizontal action bar with 8 ability slots and cooldown overlays.', metadata: { type: 'HUD', category: 'Combat', resolution: '800x100', format: 'PNG', animated: true, slots: 8, features: ['Cooldown Sweep', 'Keybind Labels', 'Active Glow'], style: 'Dark Fantasy' }, image_prompt: 'A horizontal bar with 8 ornate ability slots, some showing cooldown animations' },
    { name: 'Quest Tracker Panel', description: 'A side panel displaying active quests with checkable objectives.', metadata: { type: 'HUD', category: 'Quest', resolution: '300x400', format: 'PNG + 9-slice', animated: false, features: ['Quest Title', 'Objectives Checklist', 'Progress Bar', 'Minimize Button'], style: 'Parchment' }, image_prompt: 'A parchment side panel showing quest names with checkbox objectives and progress bars' },
    { name: 'Tooltip Frame', description: 'A dark tooltip frame that displays item stats and descriptions.', metadata: { type: 'Popup', category: 'Information', resolution: '300x400 (scalable)', format: 'PNG + 9-slice', animated: false, features: ['Item Name', 'Rarity Border', 'Stats Area', 'Flavor Text'], style: 'Dark with Gold Border' }, image_prompt: 'A dark tooltip popup showing an item name, stats, and description with a gold border' },
    { name: 'XP Progress Bar', description: 'An experience bar with level indicator and animated fill effect.', metadata: { type: 'HUD', category: 'Progression', resolution: '600x30', format: 'PNG', animated: true, features: ['Fill Animation', 'Level Number', 'XP Text', 'Glow on Gain'], style: 'Fantasy' }, image_prompt: 'A wide horizontal bar with purple glowing fill showing experience progress and level number' },
    { name: 'Buff/Debuff Icons', description: 'A set of status effect icons for buffs and debuffs.', metadata: { type: 'HUD', category: 'Status', resolution: '32x32 each', format: 'PNG', animated: false, count: 24, includes: ['Poison', 'Burn', 'Freeze', 'Haste', 'Shield', 'Regen', 'Stun', 'Bleed'], style: 'Pixel Art' }, image_prompt: 'A grid of small status effect icons including poison, fire, ice, speed, shield, and more' },
    { name: 'Character Stats Panel', description: 'A full character stats panel with attribute displays and equipment slots.', metadata: { type: 'Menu', category: 'Character', resolution: '600x800', format: 'PNG', animated: false, features: ['3D Model Viewport', 'Equipment Slots', 'Stat Bars', 'Attribute Points'], style: 'Dark Fantasy' }, image_prompt: 'A character stats panel with equipment paper doll, stat bars, and attribute displays' },
    { name: 'World Map Overlay', description: 'A full-screen world map with region markers and fog of war.', metadata: { type: 'Menu', category: 'Navigation', resolution: '1920x1080', format: 'PNG', animated: true, features: ['Region Labels', 'Fog of War', 'Quest Pins', 'Fast Travel Nodes'], style: 'Hand-drawn Fantasy' }, image_prompt: 'A hand-drawn fantasy world map with labeled regions, pins, and partially revealed fog of war' },
    { name: 'Crafting Interface', description: 'A crafting menu with recipe list, ingredient slots, and result preview.', metadata: { type: 'Menu', category: 'Crafting', resolution: '800x600', format: 'PNG', animated: true, features: ['Recipe List', 'Ingredient Slots', 'Result Preview', 'Craft Button', 'Success Rate'], style: 'Steampunk Fantasy' }, image_prompt: 'A crafting interface with ingredient slots on the left, a result preview, and recipe list' },
    { name: 'Loading Screen Frame', description: 'A decorative loading screen frame with progress bar and tip display.', metadata: { type: 'Screen', category: 'System', resolution: '1920x1080', format: 'PNG', animated: true, features: ['Progress Bar', 'Tip Text Area', 'Artwork Area', 'Animated Border'], style: 'Ornate Fantasy' }, image_prompt: 'An ornate loading screen frame with a progress bar at the bottom and a tip text area' },
    { name: 'Notification Toast', description: 'A slide-in notification for achievements, loot, and system messages.', metadata: { type: 'HUD', category: 'Notification', resolution: '400x80', format: 'PNG', animated: true, variants: ['Achievement', 'Loot', 'Warning', 'System', 'Social'], style: 'Modern Fantasy' }, image_prompt: 'Notification banners sliding in from the right showing achievement, loot, and warning styles' },
    { name: 'Skill Tree Background', description: 'A constellation-style skill tree background with node connections.', metadata: { type: 'Menu', category: 'Progression', resolution: '1920x1080', format: 'PNG', animated: true, features: ['Node Slots', 'Connection Lines', 'Branch Labels', 'Unlock Animation'], style: 'Celestial' }, image_prompt: 'A star constellation-style skill tree with glowing nodes connected by lines on a dark sky' },
  ],
  lore: [
    { name: 'The Sundering of Aethermoor', description: 'The cataclysmic event that shattered the continent 1000 years ago.', metadata: { type: 'Historical Event', era: 'First Age', importance: 'Critical', related_locations: ['Aethermoor Ruins', 'The Shattered Expanse'], related_characters: ['Archmage Valdris', 'The Five Kings'], tags: ['cataclysm', 'history', 'magic'] }, image_prompt: 'A continent breaking apart with magical energy erupting from the cracks into the sky' },
    { name: 'The Pact of Iron and Blood', description: 'The treaty that ended the century-long war between orcs and humans.', metadata: { type: 'Treaty', era: 'Second Age', importance: 'Major', related_locations: ['Ironpact Bridge', 'Neutral Zone'], related_characters: ['Warchief Grom', 'King Alderic III'], tags: ['diplomacy', 'war', 'orcs', 'humans'] }, image_prompt: 'An orc warchief and human king clasping forearms over a blood-stained iron table' },
    { name: 'The Creation Myth of the Five Flames', description: 'How the five elemental gods created the world from primordial fire.', metadata: { type: 'Mythology', era: 'Before Time', importance: 'Foundational', related_locations: ['The Five Temples'], related_characters: ['Ignar', 'Aquilis', 'Terron', 'Ventus', 'Umbra'], tags: ['creation', 'gods', 'elements', 'mythology'] }, image_prompt: 'Five different colored flames merging together to form a globe representing the world' },
    { name: 'The Whispering Library', description: 'A legendary hidden library said to contain all knowledge ever written.', metadata: { type: 'Legend', era: 'Unknown', importance: 'Major', related_locations: ['Unknown - possibly interdimensional'], related_characters: ['The Librarian (entity)'], tags: ['knowledge', 'legend', 'mystery', 'library'] }, image_prompt: 'An infinite library with floating books and whispered words visible as golden text in the air' },
    { name: 'The Undying Emperor', description: 'The tale of Emperor Kael who became a lich to rule forever, and the rebellion that sealed him.', metadata: { type: 'Historical Figure', era: 'Second Age', importance: 'Critical', related_locations: ['The Sealed Tomb', 'Old Kaelian Empire'], related_characters: ['Emperor Kael', 'The Seven Rebels'], tags: ['undead', 'empire', 'rebellion', 'lich'] }, image_prompt: 'A skeletal emperor in rotting royal robes sitting on a grand throne in a sealed tomb' },
    { name: 'The Moonsong Prophecy', description: 'An elven prophecy predicting a chosen one will reunite the broken moon.', metadata: { type: 'Prophecy', era: 'Spoken in First Age, unfulfilled', importance: 'Major', related_locations: ['Moonsong Grove', 'The Broken Moon'], related_characters: ['Oracle Selenya'], tags: ['prophecy', 'moon', 'elves', 'chosen one'] }, image_prompt: 'An elven oracle under a cracked moon singing a prophecy that appears as glowing text' },
    { name: 'The Clockwork Rebellion', description: 'When gnomish automatons gained sentience and fought for their freedom.', metadata: { type: 'Historical Event', era: 'Third Age', importance: 'Major', related_locations: ['Clockwork Foundry', 'Gnomish Republic'], related_characters: ['Unit-01', 'Inventor Gizwick'], tags: ['constructs', 'rebellion', 'gnomes', 'sentience'] }, image_prompt: 'Clockwork automatons marching through gnomish streets carrying banners of freedom' },
    { name: 'The Abyssal Incursion', description: 'The three times demons invaded the material plane and how they were repelled.', metadata: { type: 'Historical Event', era: 'Multiple Eras', importance: 'Critical', related_locations: ['The Bleeding Rift', 'Demon Gates'], related_characters: ['Demon Lord Azgoroth', 'The Sealers'], tags: ['demons', 'invasion', 'sealing', 'war'] }, image_prompt: 'Demons pouring through a red portal while heroes stand ready to fight them back' },
    { name: 'The Lost Art of Chronomancy', description: 'Time magic was once common but was banned after the Temporal Crisis.', metadata: { type: 'Magical History', era: 'Second Age', importance: 'Moderate', related_locations: ['Chronomancer Tower (ruins)'], related_characters: ['Archmage Temporis', 'The Frozen Moment'], tags: ['time', 'magic', 'forbidden', 'chronomancy'] }, image_prompt: 'A ruined tower with frozen moments of time visible as amber bubbles containing people' },
    { name: 'The Dragon Accords', description: 'The agreement between dragons and mortals that defines territorial boundaries.', metadata: { type: 'Treaty', era: 'Third Age', importance: 'Major', related_locations: ['Dragon Peaks', 'All mortal kingdoms'], related_characters: ['Elder Dragon Vyrathax', 'The Council of Crowns'], tags: ['dragons', 'diplomacy', 'territory', 'law'] }, image_prompt: 'An ancient dragon and mortal leaders standing around a massive map with territorial lines' },
    { name: 'The Plague of Whispers', description: 'A magical plague that made victims speak only in lies, nearly destroying civilization.', metadata: { type: 'Historical Event', era: 'Second Age', importance: 'Major', related_locations: ['Quarantine Cities', 'The Silent Monastery'], related_characters: ['Patient Zero (unknown)', 'Sister Veritas'], tags: ['plague', 'lies', 'cure', 'disaster'] }, image_prompt: 'People in a medieval city speaking with visible twisted dark words coming from their mouths' },
    { name: 'The Forging of the World Anvil', description: 'How the dwarves discovered and activated an artifact that lets them shape reality.', metadata: { type: 'Legend', era: 'First Age', importance: 'Moderate', related_locations: ['The World Forge', 'Deep Dwarf Citadel'], related_characters: ['Smith-King Durgan', 'The First Forgelords'], tags: ['dwarves', 'artifact', 'creation', 'forge'] }, image_prompt: 'A colossal anvil in a cavern with dwarves hammering reality itself into new shapes' },
    { name: 'The Fey Wild Crossing', description: 'How the barrier between the mortal world and Fey realm thins every century.', metadata: { type: 'Cyclical Event', era: 'All Eras', importance: 'Major', related_locations: ['Fey Crossroads', 'Mushroom Circles'], related_characters: ['The Fey Courts', 'Boundary Wardens'], tags: ['fey', 'dimensional', 'cycle', 'danger'] }, image_prompt: 'The barrier between mortal forest and colorful fey realm thinning with creatures crossing' },
    { name: 'The Cult of the Void Star', description: 'A secretive cult that worships an entity from beyond the stars.', metadata: { type: 'Organization', era: 'Current', importance: 'Growing Threat', related_locations: ['Hidden temples', 'The Observatory'], related_characters: ['The Void Prophet', 'Unknown Inner Circle'], tags: ['cult', 'cosmic horror', 'secret', 'threat'] }, image_prompt: 'Hooded cultists chanting beneath a night sky with an ominous dark star growing in the heavens' },
    { name: 'The Naming of True Things', description: 'The ancient practice of True Name magic and why it was sealed away.', metadata: { type: 'Magical History', era: 'First Age', importance: 'Moderate', related_locations: ['The Nameless Vault'], related_characters: ['The Name Keeper', 'Wordsmith Logaan'], tags: ['true names', 'magic', 'power', 'forbidden'] }, image_prompt: 'A wizard speaking a glowing word that reshapes reality around a creature being named' },
  ],
  animations: [
    { name: 'Idle Breathing', description: 'A subtle idle breathing animation for humanoid characters.', metadata: { type: 'Idle', target: 'Humanoid', frame_count: 60, fps: 30, duration: '2.0s', loopable: true, skeleton: 'Standard Humanoid', tags: ['idle', 'breathing', 'subtle'] }, image_prompt: 'Wireframe humanoid figure with subtle chest rising and falling animation' },
    { name: 'Sword Slash Combo', description: 'A three-hit sword attack combo animation.', metadata: { type: 'Combat', target: 'Humanoid', frame_count: 90, fps: 30, duration: '3.0s', loopable: false, skeleton: 'Standard Humanoid', tags: ['attack', 'sword', 'combo', 'melee'], hits: 3 }, image_prompt: 'Sequence showing three sword slash poses: horizontal, diagonal, and vertical strikes' },
    { name: 'Spell Casting Channel', description: 'A channeling animation with hands raised and energy gathering.', metadata: { type: 'Combat', target: 'Humanoid', frame_count: 120, fps: 30, duration: '4.0s', loopable: true, skeleton: 'Standard Humanoid', tags: ['magic', 'channel', 'cast', 'spell'] }, image_prompt: 'A figure with raised hands gathering swirling energy between their palms' },
    { name: 'Death Fall', description: 'A dramatic death animation where the character crumples to the ground.', metadata: { type: 'Death', target: 'Humanoid', frame_count: 45, fps: 30, duration: '1.5s', loopable: false, skeleton: 'Standard Humanoid', tags: ['death', 'fall', 'dramatic'] }, image_prompt: 'Sequence showing a character clutching their chest and falling to the ground' },
    { name: 'Sprint Cycle', description: 'A fast running cycle for player sprinting.', metadata: { type: 'Locomotion', target: 'Humanoid', frame_count: 24, fps: 30, duration: '0.8s', loopable: true, skeleton: 'Standard Humanoid', tags: ['run', 'sprint', 'locomotion', 'fast'] }, image_prompt: 'Wireframe figure in a full sprint cycle showing all key running poses' },
    { name: 'Treasure Chest Open', description: 'Animation of a treasure chest lid opening with a golden glow.', metadata: { type: 'Interaction', target: 'Prop', frame_count: 45, fps: 30, duration: '1.5s', loopable: false, skeleton: 'Chest Rig', tags: ['chest', 'open', 'loot', 'treasure'] }, image_prompt: 'A treasure chest opening with golden light spilling out and the lid swinging back' },
    { name: 'Dragon Wing Flap', description: 'A powerful wing flap cycle for large flying creatures.', metadata: { type: 'Locomotion', target: 'Dragon', frame_count: 48, fps: 24, duration: '2.0s', loopable: true, skeleton: 'Quadruped Winged', tags: ['dragon', 'fly', 'wing', 'flap'] }, image_prompt: 'A dragon in flight with wings going through full flap cycle from up to down' },
    { name: 'Potion Drink', description: 'Character brings a potion to their mouth and drinks it.', metadata: { type: 'Interaction', target: 'Humanoid', frame_count: 60, fps: 30, duration: '2.0s', loopable: false, skeleton: 'Standard Humanoid', tags: ['potion', 'drink', 'heal', 'consume'] }, image_prompt: 'A figure pulling out a potion bottle, drinking it, and wiping their mouth' },
    { name: 'Shield Block', description: 'A reactive shield block animation absorbing an incoming hit.', metadata: { type: 'Combat', target: 'Humanoid', frame_count: 30, fps: 30, duration: '1.0s', loopable: false, skeleton: 'Standard Humanoid', tags: ['shield', 'block', 'defend', 'combat'] }, image_prompt: 'A warrior bracing behind a shield as an impact sends sparks and shockwave from it' },
    { name: 'Dodge Roll', description: 'A quick evasive roll to the side for combat dodging.', metadata: { type: 'Combat', target: 'Humanoid', frame_count: 24, fps: 30, duration: '0.8s', loopable: false, skeleton: 'Standard Humanoid', tags: ['dodge', 'roll', 'evasion', 'combat'] }, image_prompt: 'A character mid-roll to the side with dust kicking up from the ground' },
    { name: 'NPC Talk Gesture', description: 'A talking animation with hand gestures for NPC dialogue.', metadata: { type: 'Social', target: 'Humanoid', frame_count: 90, fps: 30, duration: '3.0s', loopable: true, skeleton: 'Standard Humanoid', tags: ['talk', 'gesture', 'npc', 'dialogue'] }, image_prompt: 'A figure gesturing with their hands while speaking, showing different pose keyframes' },
    { name: 'Campfire Sit', description: 'A sitting animation for rest points with occasional idle movements.', metadata: { type: 'Idle', target: 'Humanoid', frame_count: 300, fps: 30, duration: '10.0s', loopable: true, skeleton: 'Standard Humanoid', tags: ['sit', 'rest', 'campfire', 'idle'] }, image_prompt: 'A character sitting cross-legged by a fire, occasionally poking it with a stick' },
    { name: 'Explosion Knockback', description: 'Character gets hit by an explosion and is thrown backward.', metadata: { type: 'Hit Reaction', target: 'Humanoid', frame_count: 60, fps: 30, duration: '2.0s', loopable: false, skeleton: 'Standard Humanoid', tags: ['explosion', 'knockback', 'hit', 'ragdoll'] }, image_prompt: 'A character being thrown backward through the air by an explosion force' },
    { name: 'Swim Cycle', description: 'A front crawl swimming animation for water traversal.', metadata: { type: 'Locomotion', target: 'Humanoid', frame_count: 48, fps: 30, duration: '1.6s', loopable: true, skeleton: 'Standard Humanoid', tags: ['swim', 'water', 'locomotion', 'crawl'] }, image_prompt: 'A figure performing front crawl swimming strokes in clear blue water' },
    { name: 'Victory Pose', description: 'A celebratory victory pose with fist pump for quest completion.', metadata: { type: 'Emote', target: 'Humanoid', frame_count: 75, fps: 30, duration: '2.5s', loopable: false, skeleton: 'Standard Humanoid', tags: ['victory', 'celebrate', 'pose', 'emote'] }, image_prompt: 'A character raising their weapon triumphantly and pumping their fist in celebration' },
  ],
};

async function seed() {
  try {
    console.log('Starting seed process...');

    // Drop tables
    await pool.query('DROP TABLE IF EXISTS assets CASCADE');
    await pool.query('DROP TABLE IF EXISTS users CASCADE');
    console.log('Dropped existing tables.');

    // Create users table
    await pool.query(`
      CREATE TABLE users (
        id SERIAL PRIMARY KEY,
        email VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        name VARCHAR(255),
        created_at TIMESTAMP DEFAULT NOW()
      )
    `);
    console.log('Created users table.');

    // Create assets table
    await pool.query(`
      CREATE TABLE assets (
        id SERIAL PRIMARY KEY,
        category VARCHAR(50) NOT NULL,
        name VARCHAR(255) NOT NULL,
        description TEXT,
        metadata JSONB DEFAULT '{}',
        image_prompt TEXT DEFAULT '',
        ai_generated BOOLEAN DEFAULT false,
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW()
      )
    `);
    console.log('Created assets table.');

    // Create demo user
    const hashedPassword = await bcrypt.hash('password123', 10);
    await pool.query(
      'INSERT INTO users (email, password, name) VALUES ($1, $2, $3)',
      ['demo@game.com', hashedPassword, 'Demo User']
    );
    console.log('Created demo user: demo@game.com');

    // Seed assets
    let totalInserted = 0;
    for (const [category, items] of Object.entries(categories)) {
      for (const item of items) {
        await pool.query(
          'INSERT INTO assets (category, name, description, metadata, image_prompt, ai_generated) VALUES ($1, $2, $3, $4, $5, $6)',
          [category, item.name, item.description, JSON.stringify(item.metadata), item.image_prompt, false]
        );
        totalInserted++;
      }
      console.log(`  Seeded ${items.length} items into "${category}"`);
    }

    console.log(`\nSeed complete!`);
    console.log(`  Total categories: ${Object.keys(categories).length}`);
    console.log(`  Total assets inserted: ${totalInserted}`);
    console.log(`  Users created: 1`);
  } catch (err) {
    console.error('Seed failed:', err);
    process.exit(1);
  } finally {
    await pool.end();
    console.log('Database connection closed.');
  }
}

seed();
